##initial run
#nse:
#  equity:
#    list-fileName: mydata/nse/EQUITY_L.csv
#    list-LoadFlag: true
#    smelist-fileName: mydata/nse/SME_EQUITY_L.csv
#    smelist-LoadFlag: true


#subsequent run
nse:
  equity:
    list-fileName: mydata/nse/EQUITY_L.csv
    list-LoadFlag: true
    smelist-fileName: mydata/nse/SME_EQUITY_L.csv
    smelist-LoadFlag: true



#personal:
#  data:
#    globalLoader: true
#    dividendDataLoader
#
