--liquibase formatted sql
--changeset partha:7_ddl_IndexMaster

CREATE TABLE IF NOT EXISTS WealthManager.IndexMaster (
            id serial4 NOT NULL,
            indexName text,
            indexKey text,
            yahoofinanceTicker text,
			CONSTRAINT uc_im_indexName UNIQUE (indexName),
            primary key (id)
);

insert into WealthManager.IndexMaster (indexName) values ('NIFTY 50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY NEXT 50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY 100');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY 200');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY 500');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MIDCAP 50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MIDCAP 100');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY SMALLCAP 100');
insert into WealthManager.IndexMaster (indexName) values ('INDIA VIX');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MIDCAP 150');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY SMALLCAP 50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY SMALLCAP 250');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MIDSMALLCAP 400');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY500 MULTICAP 50:25:25');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY LARGEMIDCAP 250');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MIDCAP SELECT');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY TOTAL MARKET');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MICROCAP 250');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY500 LARGEMIDSMALL EQUAL-CAP WEIGHTED');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY BANK');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY AUTO');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY FINANCIAL SERVICES');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY FINANCIAL SERVICES 25/50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY FMCG');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY IT');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MEDIA');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY METAL');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY PHARMA');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY PSU BANK');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY PRIVATE BANK');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY REALTY');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY HEALTHCARE INDEX');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY CONSUMER DURABLES');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY OIL & GAS');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MIDSMALL HEALTHCARE');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY FINANCIAL SERVICES EX-BANK');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MIDSMALL FINANCIAL SERVICES');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MIDSMALL IT & TELECOM');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY DIVIDEND OPPORTUNITIES 50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY GROWTH SECTORS 15');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY100 QUALITY 30');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY50 VALUE 20');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY50 TR 2X LEVERAGE');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY50 PR 2X LEVERAGE');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY50 TR 1X INVERSE');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY50 PR 1X INVERSE');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY50 DIVIDEND POINTS');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY ALPHA 50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY50 EQUAL WEIGHT');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY100 EQUAL WEIGHT');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY100 LOW VOLATILITY 30');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY200 QUALITY 30');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY ALPHA LOW-VOLATILITY 30');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY200 MOMENTUM 30');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MIDCAP150 QUALITY 50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY200 ALPHA 30');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MIDCAP150 MOMENTUM 50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY500 MOMENTUM 50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MIDSMALLCAP400 MOMENTUM QUALITY 100');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY SMALLCAP250 MOMENTUM QUALITY 100');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY TOP 10 EQUAL WEIGHT');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY ALPHA QUALITY LOW-VOLATILITY 30');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY ALPHA QUALITY VALUE LOW-VOLATILITY 30');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY HIGH BETA 50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY LOW VOLATILITY 50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY QUALITY LOW-VOLATILITY 30');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY SMALLCAP250 QUALITY 50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY TOP 15 EQUAL WEIGHT');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY100 ALPHA 30');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY200 VALUE 30');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY500 EQUAL WEIGHT');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY500 MULTICAP MOMENTUM QUALITY 50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY500 VALUE 50');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY TOP 20 EQUAL WEIGHT');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY COMMODITIES');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY INDIA CONSUMPTION');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY CPSE');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY ENERGY');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY INFRASTRUCTURE');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY100 LIQUID 15');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MIDCAP LIQUID 15');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MNC');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY PSE');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY SERVICES SECTOR');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY100 ESG SECTOR LEADERS');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY INDIA DIGITAL');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY100 ESG');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY INDIA MANUFACTURING');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY INDIA CORPORATE GROUP INDEX - TATA GROUP 25% CAP');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY500 MULTICAP INDIA MANUFACTURING 50:30:20');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY500 MULTICAP INFRASTRUCTURE 50:30:20');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY INDIA DEFENCE');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY INDIA TOURISM');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY CAPITAL MARKETS');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY EV & NEW AGE AUTOMOTIVE');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY INDIA NEW AGE CONSUMPTION');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY INDIA SELECT 5 CORPORATE GROUPS (MAATR)');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MOBILITY');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY100 ENHANCED ESG');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY CORE HOUSING');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY HOUSING');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY IPO');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY MIDSMALL INDIA CONSUMPTION');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY NON-CYCLICAL CONSUMER');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY RURAL');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY SHARIAH 25');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY TRANSPORTATION & LOGISTICS');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY50 SHARIAH');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY500 SHARIAH');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY 8-13 YR G-SEC');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY 10 YR BENCHMARK G-SEC');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY 10 YR BENCHMARK G-SEC (CLEAN PRICE)');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY 4-8 YR G-SEC INDEX');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY 11-15 YR G-SEC INDEX');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY 15 YR AND ABOVE G-SEC INDEX');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY COMPOSITE G-SEC INDEX');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY BHARAT BOND INDEX - APRIL 2025');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY BHARAT BOND INDEX - APRIL 2030');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY BHARAT BOND INDEX - APRIL 2031');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY BHARAT BOND INDEX - APRIL 2032');
insert into WealthManager.IndexMaster (indexName) values ('NIFTY BHARAT BOND INDEX - APRIL 2033');

